# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: media-tracker-api
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

provider:
  name: aws
  runtime: ruby2.7
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-2

# you can add packaging information here
#package:
#  patterns:
#    - '!exclude-me.rb'
#    - '!exclude-me-dir/**'
#    - include-me.rb
#    - include-me-dir/**

functions:
  fetch_media_list:
    handler: ddb_helpers.fetch_media_list
    events:
      - http:
          path: /api/all
          method: get
          cors: true
  create_media_entry:
    handler: ddb_helpers.create_media_entry
    events:
      - http:
          path: /api/new
          method: post
          cors: true
  delete_media_entry:
    handler: ddb_helpers.delete_media_entry
    events:
      - http:
          path: /api/delete
          method: post
          cors: true
  update_media_entry:
    handler: ddb_helpers.update_media_entry
    events:
      - http:
          path: /api/update
          method: post
          cors: true
