# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: media-tracker-api

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

package:
  patterns:
    - '!node_modules/**'
    - '!vendor/**'
    - '!spec/**'
    - '!coverage/**'
    - '!package-lock.json'
    - '!package.json'
    - '!Gemfile'
    - '!Gemfile.lock'
    - '!.idea'

provider:
  name: aws
  runtime: ruby2.7
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-2

functions:
  fetch_media_list:
    handler: handler.MediaTracker.fetch_media_list
    events:
      - http:
          path: /api/media/all
          method: get
          cors: true
  create_media_entry:
    handler: handler.MediaTracker.create_media_entry
    events:
      - http:
          path: /api/media
          method: post
          cors: true
  delete_media_entry:
    handler: handler.MediaTracker.delete_media_entry
    events:
      - http:
          path: /api/media
          method: delete
          cors: true
  update_media_entry:
    handler: handler.MediaTracker.update_media_entry
    events:
      - http:
          path: /api/media
          method: put
          cors: true
